import json
from datetime import datetime
from sqlalchemy.orm import Session
from sqlalchemy import text

DECISION_TYPES = ["hiring", "pricing", "cost_reduction", "fundraising", "growth", "product", "retention"]
INDUSTRIES = ["saas", "fintech", "marketplace", "d2c", "healthtech", "consumer_sub", "hardware", "services"]
STAGES = ["pre_seed", "seed", "series_a", "series_b_plus"]

RESEARCH_PATTERNS = [
    # ── SaaS ──────────────────────────────────────────────────────────
    {"industry": "saas", "stage": "pre_seed", "decision_type": "hiring", "success_rate": 55.0, "sample_size": 120, "median_impact": 8.0, "p25_impact": 2.0, "p75_impact": 15.0, "source": "First Round State of Startups 2024", "notes": "Technical co-founder hires most impactful at pre-seed"},
    {"industry": "saas", "stage": "pre_seed", "decision_type": "pricing", "success_rate": 62.0, "sample_size": 95, "median_impact": 12.0, "p25_impact": 4.0, "p75_impact": 22.0, "source": "OpenView Product Benchmarks 2024", "notes": "Value-based pricing outperforms cost-plus at pre-seed"},
    {"industry": "saas", "stage": "pre_seed", "decision_type": "fundraising", "success_rate": 42.0, "sample_size": 200, "median_impact": 15.0, "p25_impact": 5.0, "p75_impact": 30.0, "source": "CB Insights Venture Report 2024", "notes": "Pre-seed rounds increasingly require product demo"},
    {"industry": "saas", "stage": "pre_seed", "decision_type": "product", "success_rate": 58.0, "sample_size": 150, "median_impact": 10.0, "p25_impact": 3.0, "p75_impact": 20.0, "source": "YC Startup School Data", "notes": "MVP-first approach with 1 core feature wins"},
    {"industry": "saas", "stage": "pre_seed", "decision_type": "growth", "success_rate": 48.0, "sample_size": 110, "median_impact": 8.0, "p25_impact": 2.0, "p75_impact": 18.0, "source": "Startup Genome Report 2024", "notes": "Founder-led sales most effective at this stage"},
    {"industry": "saas", "stage": "pre_seed", "decision_type": "cost_reduction", "success_rate": 65.0, "sample_size": 80, "median_impact": 6.0, "p25_impact": 2.0, "p75_impact": 12.0, "source": "a16z Startup Metrics Guide", "notes": "Cloud cost optimization biggest lever"},
    {"industry": "saas", "stage": "pre_seed", "decision_type": "retention", "success_rate": 52.0, "sample_size": 90, "median_impact": 10.0, "p25_impact": 3.0, "p75_impact": 20.0, "source": "ChartMogul SaaS Benchmarks", "notes": "Onboarding improvements drive early retention"},

    {"industry": "saas", "stage": "seed", "decision_type": "hiring", "success_rate": 60.0, "sample_size": 180, "median_impact": 10.0, "p25_impact": 3.0, "p75_impact": 18.0, "source": "First Round State of Startups 2024", "notes": "First 10 hires set culture; eng-heavy teams outperform"},
    {"industry": "saas", "stage": "seed", "decision_type": "pricing", "success_rate": 72.0, "sample_size": 150, "median_impact": 12.5, "p25_impact": 5.0, "p75_impact": 22.0, "source": "OpenView 2024 Product Benchmarks", "notes": "10-20% price increases saw <5% logo churn"},
    {"industry": "saas", "stage": "seed", "decision_type": "cost_reduction", "success_rate": 68.0, "sample_size": 130, "median_impact": 8.0, "p25_impact": 3.0, "p75_impact": 15.0, "source": "Bessemer Cloud Index", "notes": "Infra optimization biggest lever; payroll cuts hurt morale"},
    {"industry": "saas", "stage": "seed", "decision_type": "fundraising", "success_rate": 48.0, "sample_size": 250, "median_impact": 18.0, "p25_impact": 6.0, "p75_impact": 35.0, "source": "CB Insights Venture Report 2024", "notes": "Seed rounds require $15K+ MRR for top-tier VCs"},
    {"industry": "saas", "stage": "seed", "decision_type": "growth", "success_rate": 55.0, "sample_size": 200, "median_impact": 14.0, "p25_impact": 4.0, "p75_impact": 25.0, "source": "Startup Genome Report 2024", "notes": "Content + PLG outperforms outbound at seed"},
    {"industry": "saas", "stage": "seed", "decision_type": "product", "success_rate": 62.0, "sample_size": 170, "median_impact": 11.0, "p25_impact": 4.0, "p75_impact": 22.0, "source": "YC Post-Mortems Analysis", "notes": "Feature focus beats platform play at seed"},
    {"industry": "saas", "stage": "seed", "decision_type": "retention", "success_rate": 65.0, "sample_size": 140, "median_impact": 12.0, "p25_impact": 5.0, "p75_impact": 22.0, "source": "ChartMogul SaaS Benchmarks", "notes": "Reducing time-to-value under 7 days improves retention 30%+"},

    {"industry": "saas", "stage": "series_a", "decision_type": "hiring", "success_rate": 58.0, "sample_size": 220, "median_impact": 12.0, "p25_impact": 4.0, "p75_impact": 22.0, "source": "KeyBanc SaaS Survey 2024", "notes": "VP Sales hire timing critical; too early wastes burn"},
    {"industry": "saas", "stage": "series_a", "decision_type": "pricing", "success_rate": 75.0, "sample_size": 180, "median_impact": 15.0, "p25_impact": 6.0, "p75_impact": 28.0, "source": "OpenView 2024 Product Benchmarks", "notes": "Usage-based components increase NRR 15-25%"},
    {"industry": "saas", "stage": "series_a", "decision_type": "cost_reduction", "success_rate": 70.0, "sample_size": 160, "median_impact": 10.0, "p25_impact": 4.0, "p75_impact": 18.0, "source": "Bessemer Cloud Index", "notes": "Engineering efficiency gains beat headcount cuts"},
    {"industry": "saas", "stage": "series_a", "decision_type": "fundraising", "success_rate": 52.0, "sample_size": 300, "median_impact": 22.0, "p25_impact": 8.0, "p75_impact": 40.0, "source": "CB Insights Venture Report 2024", "notes": "$1M+ ARR and 100%+ NRR expected for Series A"},
    {"industry": "saas", "stage": "series_a", "decision_type": "growth", "success_rate": 60.0, "sample_size": 250, "median_impact": 16.0, "p25_impact": 5.0, "p75_impact": 30.0, "source": "Startup Genome Report 2024", "notes": "Sales-assisted PLG outperforms pure PLG or pure sales"},
    {"industry": "saas", "stage": "series_a", "decision_type": "product", "success_rate": 65.0, "sample_size": 200, "median_impact": 14.0, "p25_impact": 5.0, "p75_impact": 25.0, "source": "a16z Marketplace 100", "notes": "Platform expansion works when core NPS > 50"},
    {"industry": "saas", "stage": "series_a", "decision_type": "retention", "success_rate": 70.0, "sample_size": 180, "median_impact": 15.0, "p25_impact": 6.0, "p75_impact": 28.0, "source": "KeyBanc SaaS Survey 2024", "notes": "CS investment yields 2-3x ROI on NRR improvement"},

    {"industry": "saas", "stage": "series_b_plus", "decision_type": "hiring", "success_rate": 62.0, "sample_size": 280, "median_impact": 14.0, "p25_impact": 5.0, "p75_impact": 25.0, "source": "KeyBanc SaaS Survey 2024", "notes": "Executive hires from scaled companies outperform"},
    {"industry": "saas", "stage": "series_b_plus", "decision_type": "pricing", "success_rate": 78.0, "sample_size": 200, "median_impact": 18.0, "p25_impact": 8.0, "p75_impact": 32.0, "source": "Bessemer Cloud Index", "notes": "Enterprise tier + consumption pricing maximizes expansion"},
    {"industry": "saas", "stage": "series_b_plus", "decision_type": "cost_reduction", "success_rate": 72.0, "sample_size": 190, "median_impact": 12.0, "p25_impact": 5.0, "p75_impact": 22.0, "source": "Bessemer Cloud Index", "notes": "Automation of manual processes yields best margin improvement"},
    {"industry": "saas", "stage": "series_b_plus", "decision_type": "fundraising", "success_rate": 55.0, "sample_size": 350, "median_impact": 25.0, "p25_impact": 10.0, "p75_impact": 45.0, "source": "CB Insights Venture Report 2024", "notes": "Rule of 40 increasingly required for Series B+"},
    {"industry": "saas", "stage": "series_b_plus", "decision_type": "growth", "success_rate": 62.0, "sample_size": 280, "median_impact": 18.0, "p25_impact": 6.0, "p75_impact": 32.0, "source": "Startup Genome Report 2024", "notes": "International expansion adds 20-40% growth when timed right"},
    {"industry": "saas", "stage": "series_b_plus", "decision_type": "product", "success_rate": 68.0, "sample_size": 230, "median_impact": 16.0, "p25_impact": 6.0, "p75_impact": 28.0, "source": "a16z Marketplace 100", "notes": "Adjacent product lines successful when sharing same buyer persona"},
    {"industry": "saas", "stage": "series_b_plus", "decision_type": "retention", "success_rate": 75.0, "sample_size": 220, "median_impact": 18.0, "p25_impact": 8.0, "p75_impact": 32.0, "source": "KeyBanc SaaS Survey 2024", "notes": "Expansion revenue > 130% NRR achievable with usage+seats"},

    # ── Fintech ───────────────────────────────────────────────────────
    {"industry": "fintech", "stage": "pre_seed", "decision_type": "hiring", "success_rate": 50.0, "sample_size": 80, "median_impact": 8.0, "p25_impact": 2.0, "p75_impact": 15.0, "source": "CB Insights Fintech Report", "notes": "Compliance expertise critical from day one"},
    {"industry": "fintech", "stage": "pre_seed", "decision_type": "pricing", "success_rate": 55.0, "sample_size": 70, "median_impact": 10.0, "p25_impact": 3.0, "p75_impact": 18.0, "source": "Stripe Atlas Fintech Guide", "notes": "Transaction fees vs subscription model key early decision"},
    {"industry": "fintech", "stage": "pre_seed", "decision_type": "fundraising", "success_rate": 38.0, "sample_size": 150, "median_impact": 14.0, "p25_impact": 4.0, "p75_impact": 28.0, "source": "CB Insights Venture Report 2024", "notes": "Fintech pre-seed requires stronger regulatory strategy narrative"},
    {"industry": "fintech", "stage": "pre_seed", "decision_type": "product", "success_rate": 52.0, "sample_size": 100, "median_impact": 10.0, "p25_impact": 3.0, "p75_impact": 20.0, "source": "a16z Fintech Newsletter", "notes": "Embedded finance approach reduces go-to-market complexity"},
    {"industry": "fintech", "stage": "pre_seed", "decision_type": "growth", "success_rate": 45.0, "sample_size": 85, "median_impact": 8.0, "p25_impact": 2.0, "p75_impact": 16.0, "source": "Startup Genome Report 2024", "notes": "Partnership-led distribution outperforms direct at pre-seed"},
    {"industry": "fintech", "stage": "pre_seed", "decision_type": "cost_reduction", "success_rate": 60.0, "sample_size": 65, "median_impact": 6.0, "p25_impact": 2.0, "p75_impact": 12.0, "source": "Stripe Atlas Fintech Guide", "notes": "Banking-as-a-service reduces infrastructure costs 50%+"},
    {"industry": "fintech", "stage": "pre_seed", "decision_type": "retention", "success_rate": 55.0, "sample_size": 75, "median_impact": 9.0, "p25_impact": 3.0, "p75_impact": 18.0, "source": "Plaid Fintech Report", "notes": "Multi-product usage from onboarding boosts stickiness"},

    {"industry": "fintech", "stage": "seed", "decision_type": "hiring", "success_rate": 55.0, "sample_size": 120, "median_impact": 10.0, "p25_impact": 3.0, "p75_impact": 18.0, "source": "First Round State of Startups 2024", "notes": "Compliance + eng hires most critical at seed"},
    {"industry": "fintech", "stage": "seed", "decision_type": "pricing", "success_rate": 65.0, "sample_size": 110, "median_impact": 12.0, "p25_impact": 4.0, "p75_impact": 22.0, "source": "Stripe Atlas Fintech Guide", "notes": "Interchange revenue diversification improves unit economics"},
    {"industry": "fintech", "stage": "seed", "decision_type": "cost_reduction", "success_rate": 62.0, "sample_size": 95, "median_impact": 8.0, "p25_impact": 3.0, "p75_impact": 15.0, "source": "CB Insights Fintech Report", "notes": "Third-party compliance tools reduce regulatory overhead 40%"},
    {"industry": "fintech", "stage": "seed", "decision_type": "fundraising", "success_rate": 44.0, "sample_size": 180, "median_impact": 16.0, "p25_impact": 5.0, "p75_impact": 30.0, "source": "CB Insights Venture Report 2024", "notes": "Regulatory approval milestones unlock next round"},
    {"industry": "fintech", "stage": "seed", "decision_type": "growth", "success_rate": 52.0, "sample_size": 140, "median_impact": 12.0, "p25_impact": 4.0, "p75_impact": 22.0, "source": "Startup Genome Report 2024", "notes": "API-first distribution via partnerships most efficient"},
    {"industry": "fintech", "stage": "seed", "decision_type": "product", "success_rate": 58.0, "sample_size": 120, "median_impact": 11.0, "p25_impact": 4.0, "p75_impact": 20.0, "source": "a16z Fintech Newsletter", "notes": "Single financial product mastery before expansion"},
    {"industry": "fintech", "stage": "seed", "decision_type": "retention", "success_rate": 60.0, "sample_size": 100, "median_impact": 11.0, "p25_impact": 4.0, "p75_impact": 20.0, "source": "Plaid Fintech Report", "notes": "Direct deposit or primary account status drives retention"},

    {"industry": "fintech", "stage": "series_a", "decision_type": "hiring", "success_rate": 58.0, "sample_size": 160, "median_impact": 12.0, "p25_impact": 4.0, "p75_impact": 22.0, "source": "KeyBanc Fintech Survey", "notes": "Risk/compliance team scaling critical for license maintenance"},
    {"industry": "fintech", "stage": "series_a", "decision_type": "pricing", "success_rate": 70.0, "sample_size": 140, "median_impact": 14.0, "p25_impact": 5.0, "p75_impact": 25.0, "source": "Stripe Atlas Fintech Guide", "notes": "Embedded finance margins improve with volume pricing"},
    {"industry": "fintech", "stage": "series_a", "decision_type": "cost_reduction", "success_rate": 65.0, "sample_size": 120, "median_impact": 10.0, "p25_impact": 4.0, "p75_impact": 18.0, "source": "CB Insights Fintech Report", "notes": "In-house compliance technology reduces per-transaction cost"},
    {"industry": "fintech", "stage": "series_a", "decision_type": "fundraising", "success_rate": 48.0, "sample_size": 220, "median_impact": 20.0, "p25_impact": 7.0, "p75_impact": 38.0, "source": "CB Insights Venture Report 2024", "notes": "Fintech Series A requires proven unit economics + compliance track record"},
    {"industry": "fintech", "stage": "series_a", "decision_type": "growth", "success_rate": 58.0, "sample_size": 180, "median_impact": 15.0, "p25_impact": 5.0, "p75_impact": 28.0, "source": "Startup Genome Report 2024", "notes": "B2B2C distribution scales faster than direct-to-consumer in fintech"},
    {"industry": "fintech", "stage": "series_a", "decision_type": "product", "success_rate": 62.0, "sample_size": 150, "median_impact": 13.0, "p25_impact": 5.0, "p75_impact": 24.0, "source": "a16z Fintech Newsletter", "notes": "Multi-product fintech stacks increase ARPU 3-5x"},
    {"industry": "fintech", "stage": "series_a", "decision_type": "retention", "success_rate": 68.0, "sample_size": 130, "median_impact": 14.0, "p25_impact": 5.0, "p75_impact": 25.0, "source": "Plaid Fintech Report", "notes": "Switching costs from data portability create natural moats"},

    {"industry": "fintech", "stage": "series_b_plus", "decision_type": "hiring", "success_rate": 60.0, "sample_size": 200, "median_impact": 14.0, "p25_impact": 5.0, "p75_impact": 25.0, "source": "KeyBanc Fintech Survey", "notes": "Experienced risk/compliance leaders from large banks add credibility"},
    {"industry": "fintech", "stage": "series_b_plus", "decision_type": "pricing", "success_rate": 74.0, "sample_size": 170, "median_impact": 16.0, "p25_impact": 6.0, "p75_impact": 30.0, "source": "Bessemer Cloud Index", "notes": "Tiered enterprise pricing unlocks institutional revenue"},
    {"industry": "fintech", "stage": "series_b_plus", "decision_type": "cost_reduction", "success_rate": 68.0, "sample_size": 150, "median_impact": 12.0, "p25_impact": 5.0, "p75_impact": 22.0, "source": "CB Insights Fintech Report", "notes": "In-house processing vs third-party reduces COGS 25-40%"},
    {"industry": "fintech", "stage": "series_b_plus", "decision_type": "fundraising", "success_rate": 52.0, "sample_size": 280, "median_impact": 24.0, "p25_impact": 9.0, "p75_impact": 42.0, "source": "CB Insights Venture Report 2024", "notes": "Path to profitability increasingly required for Series B+"},
    {"industry": "fintech", "stage": "series_b_plus", "decision_type": "growth", "success_rate": 60.0, "sample_size": 220, "median_impact": 17.0, "p25_impact": 6.0, "p75_impact": 30.0, "source": "Startup Genome Report 2024", "notes": "Geographic expansion in fintech requires local license partnerships"},
    {"industry": "fintech", "stage": "series_b_plus", "decision_type": "product", "success_rate": 65.0, "sample_size": 180, "median_impact": 15.0, "p25_impact": 6.0, "p75_impact": 28.0, "source": "a16z Fintech Newsletter", "notes": "Lending/credit products add highest marginal revenue but increase risk"},
    {"industry": "fintech", "stage": "series_b_plus", "decision_type": "retention", "success_rate": 72.0, "sample_size": 170, "median_impact": 16.0, "p25_impact": 7.0, "p75_impact": 30.0, "source": "Plaid Fintech Report", "notes": "Full banking stack creates near-zero voluntary churn"},

    # ── Marketplace ───────────────────────────────────────────────────
    {"industry": "marketplace", "stage": "pre_seed", "decision_type": "hiring", "success_rate": 50.0, "sample_size": 75, "median_impact": 7.0, "p25_impact": 2.0, "p75_impact": 14.0, "source": "a16z Marketplace 100", "notes": "Supply-side ops hires most critical early"},
    {"industry": "marketplace", "stage": "pre_seed", "decision_type": "pricing", "success_rate": 55.0, "sample_size": 65, "median_impact": 9.0, "p25_impact": 3.0, "p75_impact": 18.0, "source": "Lenny's Newsletter Marketplace Data", "notes": "Lower take rates accelerate supply acquisition"},
    {"industry": "marketplace", "stage": "pre_seed", "decision_type": "growth", "success_rate": 52.0, "sample_size": 90, "median_impact": 10.0, "p25_impact": 3.0, "p75_impact": 20.0, "source": "Startup Genome Report 2024", "notes": "Supply-constrained marketplaces should build supply first"},
    {"industry": "marketplace", "stage": "pre_seed", "decision_type": "product", "success_rate": 55.0, "sample_size": 80, "median_impact": 9.0, "p25_impact": 3.0, "p75_impact": 18.0, "source": "a16z Marketplace 100", "notes": "Manual matching before algorithm investment"},
    {"industry": "marketplace", "stage": "pre_seed", "decision_type": "fundraising", "success_rate": 40.0, "sample_size": 130, "median_impact": 13.0, "p25_impact": 4.0, "p75_impact": 25.0, "source": "CB Insights Venture Report 2024", "notes": "GMV growth rate more important than absolute GMV at pre-seed"},
    {"industry": "marketplace", "stage": "pre_seed", "decision_type": "cost_reduction", "success_rate": 58.0, "sample_size": 55, "median_impact": 6.0, "p25_impact": 2.0, "p75_impact": 12.0, "source": "First Round Capital Blog", "notes": "Do-things-that-dont-scale first, optimize later"},
    {"industry": "marketplace", "stage": "pre_seed", "decision_type": "retention", "success_rate": 48.0, "sample_size": 70, "median_impact": 8.0, "p25_impact": 2.0, "p75_impact": 16.0, "source": "Lenny's Newsletter Marketplace Data", "notes": "Transaction frequency is the key retention metric"},

    {"industry": "marketplace", "stage": "seed", "decision_type": "hiring", "success_rate": 55.0, "sample_size": 110, "median_impact": 9.0, "p25_impact": 3.0, "p75_impact": 16.0, "source": "a16z Marketplace 100", "notes": "Community managers drive marketplace engagement 2x"},
    {"industry": "marketplace", "stage": "seed", "decision_type": "pricing", "success_rate": 60.0, "sample_size": 100, "median_impact": 11.0, "p25_impact": 4.0, "p75_impact": 20.0, "source": "Lenny's Newsletter Marketplace Data", "notes": "Take rate sweet spot 12-18% for most verticals"},
    {"industry": "marketplace", "stage": "seed", "decision_type": "growth", "success_rate": 58.0, "sample_size": 130, "median_impact": 13.0, "p25_impact": 4.0, "p75_impact": 24.0, "source": "Startup Genome Report 2024", "notes": "Geographic density beats geographic breadth"},
    {"industry": "marketplace", "stage": "seed", "decision_type": "product", "success_rate": 60.0, "sample_size": 110, "median_impact": 11.0, "p25_impact": 4.0, "p75_impact": 20.0, "source": "a16z Marketplace 100", "notes": "Managed marketplace model increases take rate 2-3x"},
    {"industry": "marketplace", "stage": "seed", "decision_type": "fundraising", "success_rate": 45.0, "sample_size": 170, "median_impact": 15.0, "p25_impact": 5.0, "p75_impact": 28.0, "source": "CB Insights Venture Report 2024", "notes": "Liquidity metrics (match rate, time to transaction) key for VCs"},
    {"industry": "marketplace", "stage": "seed", "decision_type": "cost_reduction", "success_rate": 62.0, "sample_size": 85, "median_impact": 7.0, "p25_impact": 3.0, "p75_impact": 14.0, "source": "First Round Capital Blog", "notes": "Automating supply-side operations biggest cost lever"},
    {"industry": "marketplace", "stage": "seed", "decision_type": "retention", "success_rate": 55.0, "sample_size": 95, "median_impact": 10.0, "p25_impact": 3.0, "p75_impact": 19.0, "source": "Lenny's Newsletter Marketplace Data", "notes": "Supply quality curation drives demand retention"},

    {"industry": "marketplace", "stage": "series_a", "decision_type": "hiring", "success_rate": 58.0, "sample_size": 140, "median_impact": 11.0, "p25_impact": 4.0, "p75_impact": 20.0, "source": "a16z Marketplace 100", "notes": "Data/ML hires improve matching quality"},
    {"industry": "marketplace", "stage": "series_a", "decision_type": "pricing", "success_rate": 65.0, "sample_size": 120, "median_impact": 13.0, "p25_impact": 5.0, "p75_impact": 24.0, "source": "Lenny's Newsletter Marketplace Data", "notes": "Value-added services increase effective take rate"},
    {"industry": "marketplace", "stage": "series_a", "decision_type": "growth", "success_rate": 60.0, "sample_size": 160, "median_impact": 15.0, "p25_impact": 5.0, "p75_impact": 28.0, "source": "Startup Genome Report 2024", "notes": "Category expansion after density threshold in core vertical"},
    {"industry": "marketplace", "stage": "series_a", "decision_type": "product", "success_rate": 62.0, "sample_size": 130, "median_impact": 13.0, "p25_impact": 5.0, "p75_impact": 24.0, "source": "a16z Marketplace 100", "notes": "Payments integration increases platform stickiness"},
    {"industry": "marketplace", "stage": "series_a", "decision_type": "fundraising", "success_rate": 50.0, "sample_size": 200, "median_impact": 18.0, "p25_impact": 6.0, "p75_impact": 34.0, "source": "CB Insights Venture Report 2024", "notes": "Unit economics at market level required for Series A"},
    {"industry": "marketplace", "stage": "series_a", "decision_type": "cost_reduction", "success_rate": 65.0, "sample_size": 110, "median_impact": 9.0, "p25_impact": 3.0, "p75_impact": 17.0, "source": "First Round Capital Blog", "notes": "Algorithm-driven pricing reduces manual intervention 60%"},
    {"industry": "marketplace", "stage": "series_a", "decision_type": "retention", "success_rate": 62.0, "sample_size": 120, "median_impact": 13.0, "p25_impact": 5.0, "p75_impact": 24.0, "source": "Lenny's Newsletter Marketplace Data", "notes": "Subscription models for power users boost retention 25%"},

    {"industry": "marketplace", "stage": "series_b_plus", "decision_type": "hiring", "success_rate": 60.0, "sample_size": 170, "median_impact": 13.0, "p25_impact": 5.0, "p75_impact": 24.0, "source": "a16z Marketplace 100", "notes": "Ops leaders from logistics/supply chain backgrounds excel"},
    {"industry": "marketplace", "stage": "series_b_plus", "decision_type": "pricing", "success_rate": 70.0, "sample_size": 150, "median_impact": 15.0, "p25_impact": 6.0, "p75_impact": 28.0, "source": "Lenny's Newsletter Marketplace Data", "notes": "Advertising + SaaS tools layer additional revenue on take rate"},
    {"industry": "marketplace", "stage": "series_b_plus", "decision_type": "growth", "success_rate": 62.0, "sample_size": 190, "median_impact": 16.0, "p25_impact": 6.0, "p75_impact": 30.0, "source": "Startup Genome Report 2024", "notes": "M&A of smaller vertical marketplaces accelerates growth"},
    {"industry": "marketplace", "stage": "series_b_plus", "decision_type": "product", "success_rate": 65.0, "sample_size": 160, "median_impact": 15.0, "p25_impact": 6.0, "p75_impact": 28.0, "source": "a16z Marketplace 100", "notes": "Fintech/logistics integration deepens moat"},
    {"industry": "marketplace", "stage": "series_b_plus", "decision_type": "fundraising", "success_rate": 54.0, "sample_size": 240, "median_impact": 22.0, "p25_impact": 8.0, "p75_impact": 40.0, "source": "CB Insights Venture Report 2024", "notes": "Network effects evidence and market share data critical"},
    {"industry": "marketplace", "stage": "series_b_plus", "decision_type": "cost_reduction", "success_rate": 68.0, "sample_size": 140, "median_impact": 11.0, "p25_impact": 4.0, "p75_impact": 20.0, "source": "First Round Capital Blog", "notes": "Automated trust/safety reduces support costs 30-50%"},
    {"industry": "marketplace", "stage": "series_b_plus", "decision_type": "retention", "success_rate": 68.0, "sample_size": 150, "median_impact": 15.0, "p25_impact": 6.0, "p75_impact": 28.0, "source": "Lenny's Newsletter Marketplace Data", "notes": "Loyalty programs and data lock-in create switching costs"},

    # ── D2C ───────────────────────────────────────────────────────────
    {"industry": "d2c", "stage": "pre_seed", "decision_type": "hiring", "success_rate": 50.0, "sample_size": 70, "median_impact": 7.0, "p25_impact": 2.0, "p75_impact": 14.0, "source": "Shopify Commerce Report", "notes": "Creative/brand hires more impactful than ops at pre-seed"},
    {"industry": "d2c", "stage": "pre_seed", "decision_type": "pricing", "success_rate": 58.0, "sample_size": 80, "median_impact": 10.0, "p25_impact": 3.0, "p75_impact": 18.0, "source": "Reforge Growth Series", "notes": "Premium pricing with clear differentiation outperforms discount"},
    {"industry": "d2c", "stage": "pre_seed", "decision_type": "growth", "success_rate": 52.0, "sample_size": 90, "median_impact": 9.0, "p25_impact": 3.0, "p75_impact": 18.0, "source": "Startup Genome Report 2024", "notes": "Social-first brands with organic reach before paid"},
    {"industry": "d2c", "stage": "pre_seed", "decision_type": "product", "success_rate": 55.0, "sample_size": 85, "median_impact": 9.0, "p25_impact": 3.0, "p75_impact": 18.0, "source": "CB Insights D2C Report", "notes": "Single hero product before line expansion"},
    {"industry": "d2c", "stage": "pre_seed", "decision_type": "fundraising", "success_rate": 38.0, "sample_size": 120, "median_impact": 12.0, "p25_impact": 4.0, "p75_impact": 24.0, "source": "CB Insights Venture Report 2024", "notes": "Community size + engagement metrics matter more than revenue"},
    {"industry": "d2c", "stage": "pre_seed", "decision_type": "cost_reduction", "success_rate": 60.0, "sample_size": 60, "median_impact": 6.0, "p25_impact": 2.0, "p75_impact": 12.0, "source": "Shopify Commerce Report", "notes": "Dropship/3PL before owned inventory"},
    {"industry": "d2c", "stage": "pre_seed", "decision_type": "retention", "success_rate": 45.0, "sample_size": 70, "median_impact": 8.0, "p25_impact": 2.0, "p75_impact": 16.0, "source": "Reforge Growth Series", "notes": "Subscription box model improves retention 2-3x vs one-time"},

    {"industry": "d2c", "stage": "seed", "decision_type": "hiring", "success_rate": 52.0, "sample_size": 100, "median_impact": 8.0, "p25_impact": 3.0, "p75_impact": 16.0, "source": "Shopify Commerce Report", "notes": "Performance marketing hire critical for scaling paid channels"},
    {"industry": "d2c", "stage": "seed", "decision_type": "pricing", "success_rate": 62.0, "sample_size": 110, "median_impact": 11.0, "p25_impact": 4.0, "p75_impact": 20.0, "source": "Reforge Growth Series", "notes": "Bundle pricing increases AOV 20-35%"},
    {"industry": "d2c", "stage": "seed", "decision_type": "growth", "success_rate": 55.0, "sample_size": 130, "median_impact": 12.0, "p25_impact": 4.0, "p75_impact": 22.0, "source": "Startup Genome Report 2024", "notes": "Influencer partnerships outperform broad paid media"},
    {"industry": "d2c", "stage": "seed", "decision_type": "product", "success_rate": 58.0, "sample_size": 110, "median_impact": 10.0, "p25_impact": 4.0, "p75_impact": 20.0, "source": "CB Insights D2C Report", "notes": "Second product line within 12 months boosts LTV"},
    {"industry": "d2c", "stage": "seed", "decision_type": "fundraising", "success_rate": 42.0, "sample_size": 160, "median_impact": 14.0, "p25_impact": 5.0, "p75_impact": 28.0, "source": "CB Insights Venture Report 2024", "notes": "Repeat purchase rate and CAC payback key metrics"},
    {"industry": "d2c", "stage": "seed", "decision_type": "cost_reduction", "success_rate": 60.0, "sample_size": 80, "median_impact": 7.0, "p25_impact": 3.0, "p75_impact": 14.0, "source": "Shopify Commerce Report", "notes": "Direct supplier relationships improve COGS 15-25%"},
    {"industry": "d2c", "stage": "seed", "decision_type": "retention", "success_rate": 50.0, "sample_size": 95, "median_impact": 10.0, "p25_impact": 3.0, "p75_impact": 19.0, "source": "Reforge Growth Series", "notes": "Email/SMS lifecycle flows drive 30%+ repeat purchases"},

    {"industry": "d2c", "stage": "series_a", "decision_type": "hiring", "success_rate": 55.0, "sample_size": 130, "median_impact": 10.0, "p25_impact": 4.0, "p75_impact": 18.0, "source": "Shopify Commerce Report", "notes": "Supply chain lead hire reduces fulfillment costs at scale"},
    {"industry": "d2c", "stage": "series_a", "decision_type": "pricing", "success_rate": 65.0, "sample_size": 120, "median_impact": 13.0, "p25_impact": 5.0, "p75_impact": 24.0, "source": "Reforge Growth Series", "notes": "Subscription + one-time hybrid maximizes LTV"},
    {"industry": "d2c", "stage": "series_a", "decision_type": "growth", "success_rate": 58.0, "sample_size": 150, "median_impact": 14.0, "p25_impact": 5.0, "p75_impact": 26.0, "source": "Startup Genome Report 2024", "notes": "Retail distribution adds 30-50% revenue but compresses margins"},
    {"industry": "d2c", "stage": "series_a", "decision_type": "product", "success_rate": 60.0, "sample_size": 120, "median_impact": 12.0, "p25_impact": 4.0, "p75_impact": 22.0, "source": "CB Insights D2C Report", "notes": "Category expansion when hero product has 40%+ repeat rate"},
    {"industry": "d2c", "stage": "series_a", "decision_type": "fundraising", "success_rate": 46.0, "sample_size": 190, "median_impact": 17.0, "p25_impact": 6.0, "p75_impact": 32.0, "source": "CB Insights Venture Report 2024", "notes": "LTV:CAC > 3x and positive contribution margin required"},
    {"industry": "d2c", "stage": "series_a", "decision_type": "cost_reduction", "success_rate": 64.0, "sample_size": 100, "median_impact": 9.0, "p25_impact": 3.0, "p75_impact": 16.0, "source": "Shopify Commerce Report", "notes": "Owned fulfillment center breaks even at ~$5M revenue"},
    {"industry": "d2c", "stage": "series_a", "decision_type": "retention", "success_rate": 58.0, "sample_size": 110, "median_impact": 12.0, "p25_impact": 5.0, "p75_impact": 22.0, "source": "Reforge Growth Series", "notes": "Loyalty programs increase 2nd purchase rate 20-30%"},

    {"industry": "d2c", "stage": "series_b_plus", "decision_type": "hiring", "success_rate": 58.0, "sample_size": 160, "median_impact": 12.0, "p25_impact": 4.0, "p75_impact": 22.0, "source": "Shopify Commerce Report", "notes": "Retail/wholesale team hires for omnichannel expansion"},
    {"industry": "d2c", "stage": "series_b_plus", "decision_type": "pricing", "success_rate": 68.0, "sample_size": 140, "median_impact": 15.0, "p25_impact": 6.0, "p75_impact": 28.0, "source": "Reforge Growth Series", "notes": "Premium tiers and personalization increase ARPU 25-40%"},
    {"industry": "d2c", "stage": "series_b_plus", "decision_type": "growth", "success_rate": 60.0, "sample_size": 180, "median_impact": 16.0, "p25_impact": 6.0, "p75_impact": 30.0, "source": "Startup Genome Report 2024", "notes": "International expansion + wholesale channels for scale"},
    {"industry": "d2c", "stage": "series_b_plus", "decision_type": "product", "success_rate": 62.0, "sample_size": 140, "median_impact": 14.0, "p25_impact": 5.0, "p75_impact": 26.0, "source": "CB Insights D2C Report", "notes": "Private label adjacencies maximize brand equity"},
    {"industry": "d2c", "stage": "series_b_plus", "decision_type": "fundraising", "success_rate": 50.0, "sample_size": 220, "median_impact": 20.0, "p25_impact": 8.0, "p75_impact": 38.0, "source": "CB Insights Venture Report 2024", "notes": "Omnichannel metrics and brand strength dominate at this stage"},
    {"industry": "d2c", "stage": "series_b_plus", "decision_type": "cost_reduction", "success_rate": 66.0, "sample_size": 120, "median_impact": 10.0, "p25_impact": 4.0, "p75_impact": 18.0, "source": "Shopify Commerce Report", "notes": "Vertical integration reduces COGS 20-35%"},
    {"industry": "d2c", "stage": "series_b_plus", "decision_type": "retention", "success_rate": 62.0, "sample_size": 130, "median_impact": 14.0, "p25_impact": 5.0, "p75_impact": 26.0, "source": "Reforge Growth Series", "notes": "Community + membership models create 50%+ annual retention"},

    # ── Healthtech ────────────────────────────────────────────────────
    {"industry": "healthtech", "stage": "pre_seed", "decision_type": "hiring", "success_rate": 48.0, "sample_size": 65, "median_impact": 7.0, "p25_impact": 2.0, "p75_impact": 14.0, "source": "Rock Health Digital Health Report", "notes": "Clinical advisors essential for regulatory navigation"},
    {"industry": "healthtech", "stage": "pre_seed", "decision_type": "pricing", "success_rate": 52.0, "sample_size": 55, "median_impact": 8.0, "p25_impact": 2.0, "p75_impact": 16.0, "source": "a16z Bio + Health Newsletter", "notes": "Per-patient or outcomes-based pricing gaining traction"},
    {"industry": "healthtech", "stage": "pre_seed", "decision_type": "product", "success_rate": 50.0, "sample_size": 75, "median_impact": 8.0, "p25_impact": 2.0, "p75_impact": 16.0, "source": "Rock Health Digital Health Report", "notes": "Clinical validation study critical before scaling"},
    {"industry": "healthtech", "stage": "pre_seed", "decision_type": "fundraising", "success_rate": 40.0, "sample_size": 110, "median_impact": 12.0, "p25_impact": 4.0, "p75_impact": 24.0, "source": "CB Insights Venture Report 2024", "notes": "FDA pathway clarity significantly improves fundability"},
    {"industry": "healthtech", "stage": "pre_seed", "decision_type": "growth", "success_rate": 42.0, "sample_size": 70, "median_impact": 7.0, "p25_impact": 2.0, "p75_impact": 14.0, "source": "Startup Genome Report 2024", "notes": "Health system partnerships > direct-to-patient at pre-seed"},
    {"industry": "healthtech", "stage": "pre_seed", "decision_type": "cost_reduction", "success_rate": 58.0, "sample_size": 50, "median_impact": 5.0, "p25_impact": 2.0, "p75_impact": 10.0, "source": "a16z Bio + Health Newsletter", "notes": "Cloud-based HIPAA compliance reduces infrastructure cost 40%"},
    {"industry": "healthtech", "stage": "pre_seed", "decision_type": "retention", "success_rate": 55.0, "sample_size": 60, "median_impact": 9.0, "p25_impact": 3.0, "p75_impact": 18.0, "source": "Rock Health Digital Health Report", "notes": "EHR integration is the key stickiness factor"},

    {"industry": "healthtech", "stage": "seed", "decision_type": "hiring", "success_rate": 52.0, "sample_size": 95, "median_impact": 9.0, "p25_impact": 3.0, "p75_impact": 16.0, "source": "Rock Health Digital Health Report", "notes": "Regulatory + clinical affairs hires accelerate approval timelines"},
    {"industry": "healthtech", "stage": "seed", "decision_type": "pricing", "success_rate": 58.0, "sample_size": 80, "median_impact": 10.0, "p25_impact": 3.0, "p75_impact": 18.0, "source": "a16z Bio + Health Newsletter", "notes": "ROI-based pricing aligns incentives with health system buyers"},
    {"industry": "healthtech", "stage": "seed", "decision_type": "product", "success_rate": 55.0, "sample_size": 100, "median_impact": 10.0, "p25_impact": 3.0, "p75_impact": 19.0, "source": "Rock Health Digital Health Report", "notes": "Interoperability with existing EHR systems is non-negotiable"},
    {"industry": "healthtech", "stage": "seed", "decision_type": "fundraising", "success_rate": 44.0, "sample_size": 150, "median_impact": 15.0, "p25_impact": 5.0, "p75_impact": 28.0, "source": "CB Insights Venture Report 2024", "notes": "Pilot data from 2+ health systems strengthens seed round"},
    {"industry": "healthtech", "stage": "seed", "decision_type": "growth", "success_rate": 48.0, "sample_size": 100, "median_impact": 10.0, "p25_impact": 3.0, "p75_impact": 19.0, "source": "Startup Genome Report 2024", "notes": "Channel partnerships with distributors scale faster than direct"},
    {"industry": "healthtech", "stage": "seed", "decision_type": "cost_reduction", "success_rate": 60.0, "sample_size": 70, "median_impact": 7.0, "p25_impact": 2.0, "p75_impact": 13.0, "source": "a16z Bio + Health Newsletter", "notes": "Shared services for compliance reduce overhead 30%"},
    {"industry": "healthtech", "stage": "seed", "decision_type": "retention", "success_rate": 60.0, "sample_size": 85, "median_impact": 11.0, "p25_impact": 4.0, "p75_impact": 20.0, "source": "Rock Health Digital Health Report", "notes": "Clinical outcome tracking drives multi-year contracts"},

    {"industry": "healthtech", "stage": "series_a", "decision_type": "hiring", "success_rate": 55.0, "sample_size": 125, "median_impact": 11.0, "p25_impact": 4.0, "p75_impact": 20.0, "source": "Rock Health Digital Health Report", "notes": "Commercial leader with payer relationship experience critical"},
    {"industry": "healthtech", "stage": "series_a", "decision_type": "pricing", "success_rate": 62.0, "sample_size": 100, "median_impact": 12.0, "p25_impact": 4.0, "p75_impact": 22.0, "source": "a16z Bio + Health Newsletter", "notes": "Risk-sharing contracts with health plans increase deal size"},
    {"industry": "healthtech", "stage": "series_a", "decision_type": "product", "success_rate": 58.0, "sample_size": 110, "median_impact": 12.0, "p25_impact": 4.0, "p75_impact": 22.0, "source": "Rock Health Digital Health Report", "notes": "Platform approach works when core clinical module has strong evidence"},
    {"industry": "healthtech", "stage": "series_a", "decision_type": "fundraising", "success_rate": 48.0, "sample_size": 180, "median_impact": 18.0, "p25_impact": 6.0, "p75_impact": 34.0, "source": "CB Insights Venture Report 2024", "notes": "Clinical evidence + reimbursement strategy drives Series A valuation"},
    {"industry": "healthtech", "stage": "series_a", "decision_type": "growth", "success_rate": 52.0, "sample_size": 130, "median_impact": 13.0, "p25_impact": 4.0, "p75_impact": 24.0, "source": "Startup Genome Report 2024", "notes": "Payer partnerships unlock large patient populations"},
    {"industry": "healthtech", "stage": "series_a", "decision_type": "cost_reduction", "success_rate": 62.0, "sample_size": 90, "median_impact": 9.0, "p25_impact": 3.0, "p75_impact": 16.0, "source": "a16z Bio + Health Newsletter", "notes": "Automation of care coordination reduces cost per patient 25%"},
    {"industry": "healthtech", "stage": "series_a", "decision_type": "retention", "success_rate": 65.0, "sample_size": 100, "median_impact": 13.0, "p25_impact": 5.0, "p75_impact": 24.0, "source": "Rock Health Digital Health Report", "notes": "Multi-year contracts with outcome guarantees lock in customers"},

    {"industry": "healthtech", "stage": "series_b_plus", "decision_type": "hiring", "success_rate": 58.0, "sample_size": 155, "median_impact": 13.0, "p25_impact": 5.0, "p75_impact": 24.0, "source": "Rock Health Digital Health Report", "notes": "Government affairs hires open Medicare/Medicaid channels"},
    {"industry": "healthtech", "stage": "series_b_plus", "decision_type": "pricing", "success_rate": 66.0, "sample_size": 120, "median_impact": 14.0, "p25_impact": 5.0, "p75_impact": 26.0, "source": "a16z Bio + Health Newsletter", "notes": "Capitated pricing models align with value-based care trends"},
    {"industry": "healthtech", "stage": "series_b_plus", "decision_type": "product", "success_rate": 62.0, "sample_size": 130, "median_impact": 14.0, "p25_impact": 5.0, "p75_impact": 26.0, "source": "Rock Health Digital Health Report", "notes": "AI-driven clinical decision support adds premium pricing tier"},
    {"industry": "healthtech", "stage": "series_b_plus", "decision_type": "fundraising", "success_rate": 52.0, "sample_size": 210, "median_impact": 22.0, "p25_impact": 8.0, "p75_impact": 40.0, "source": "CB Insights Venture Report 2024", "notes": "Path to profitability through network effects critical at B+"},
    {"industry": "healthtech", "stage": "series_b_plus", "decision_type": "growth", "success_rate": 55.0, "sample_size": 160, "median_impact": 15.0, "p25_impact": 5.0, "p75_impact": 28.0, "source": "Startup Genome Report 2024", "notes": "Life sciences partnerships for drug development adjacency"},
    {"industry": "healthtech", "stage": "series_b_plus", "decision_type": "cost_reduction", "success_rate": 65.0, "sample_size": 110, "median_impact": 11.0, "p25_impact": 4.0, "p75_impact": 20.0, "source": "a16z Bio + Health Newsletter", "notes": "Scale economics in data processing reduce per-claim cost"},
    {"industry": "healthtech", "stage": "series_b_plus", "decision_type": "retention", "success_rate": 70.0, "sample_size": 120, "median_impact": 15.0, "p25_impact": 6.0, "p75_impact": 28.0, "source": "Rock Health Digital Health Report", "notes": "Data network effects create near-zero churn once embedded"},

    # ── Consumer Subscription ─────────────────────────────────────────
    {"industry": "consumer_sub", "stage": "pre_seed", "decision_type": "hiring", "success_rate": 48.0, "sample_size": 65, "median_impact": 7.0, "p25_impact": 2.0, "p75_impact": 14.0, "source": "Subscription Economy Index", "notes": "Content/creative talent most impactful early"},
    {"industry": "consumer_sub", "stage": "pre_seed", "decision_type": "pricing", "success_rate": 55.0, "sample_size": 75, "median_impact": 9.0, "p25_impact": 3.0, "p75_impact": 18.0, "source": "Zuora Subscription Economy Report", "notes": "Annual pre-pay discount drives early cash flow"},
    {"industry": "consumer_sub", "stage": "pre_seed", "decision_type": "growth", "success_rate": 52.0, "sample_size": 80, "median_impact": 9.0, "p25_impact": 3.0, "p75_impact": 18.0, "source": "Startup Genome Report 2024", "notes": "Viral/referral loops most capital-efficient growth channel"},
    {"industry": "consumer_sub", "stage": "pre_seed", "decision_type": "product", "success_rate": 50.0, "sample_size": 70, "median_impact": 8.0, "p25_impact": 2.0, "p75_impact": 16.0, "source": "First Round State of Startups 2024", "notes": "Habit-forming daily use more important than feature breadth"},
    {"industry": "consumer_sub", "stage": "pre_seed", "decision_type": "fundraising", "success_rate": 40.0, "sample_size": 120, "median_impact": 12.0, "p25_impact": 4.0, "p75_impact": 24.0, "source": "CB Insights Venture Report 2024", "notes": "DAU/MAU ratio strongest predictor of fundability"},
    {"industry": "consumer_sub", "stage": "pre_seed", "decision_type": "cost_reduction", "success_rate": 58.0, "sample_size": 50, "median_impact": 5.0, "p25_impact": 2.0, "p75_impact": 10.0, "source": "Zuora Subscription Economy Report", "notes": "No-code tools for onboarding reduce eng costs 40%"},
    {"industry": "consumer_sub", "stage": "pre_seed", "decision_type": "retention", "success_rate": 45.0, "sample_size": 65, "median_impact": 8.0, "p25_impact": 2.0, "p75_impact": 16.0, "source": "Subscription Economy Index", "notes": "Push notification strategy drives 20%+ retention improvement"},

    {"industry": "consumer_sub", "stage": "seed", "decision_type": "hiring", "success_rate": 52.0, "sample_size": 90, "median_impact": 8.0, "p25_impact": 3.0, "p75_impact": 16.0, "source": "Subscription Economy Index", "notes": "Growth engineer hire accelerates experimentation velocity"},
    {"industry": "consumer_sub", "stage": "seed", "decision_type": "pricing", "success_rate": 60.0, "sample_size": 100, "median_impact": 11.0, "p25_impact": 4.0, "p75_impact": 20.0, "source": "Zuora Subscription Economy Report", "notes": "Freemium-to-paid conversion optimization is key lever"},
    {"industry": "consumer_sub", "stage": "seed", "decision_type": "growth", "success_rate": 55.0, "sample_size": 120, "median_impact": 12.0, "p25_impact": 4.0, "p75_impact": 22.0, "source": "Startup Genome Report 2024", "notes": "Creator/influencer partnerships scale organic acquisition"},
    {"industry": "consumer_sub", "stage": "seed", "decision_type": "product", "success_rate": 55.0, "sample_size": 100, "median_impact": 10.0, "p25_impact": 3.0, "p75_impact": 19.0, "source": "First Round State of Startups 2024", "notes": "Social features increase engagement 40%+"},
    {"industry": "consumer_sub", "stage": "seed", "decision_type": "fundraising", "success_rate": 42.0, "sample_size": 150, "median_impact": 14.0, "p25_impact": 5.0, "p75_impact": 28.0, "source": "CB Insights Venture Report 2024", "notes": "Trial-to-paid conversion and D30 retention key metrics"},
    {"industry": "consumer_sub", "stage": "seed", "decision_type": "cost_reduction", "success_rate": 60.0, "sample_size": 70, "median_impact": 6.0, "p25_impact": 2.0, "p75_impact": 12.0, "source": "Zuora Subscription Economy Report", "notes": "CDN and content delivery optimization biggest tech cost lever"},
    {"industry": "consumer_sub", "stage": "seed", "decision_type": "retention", "success_rate": 50.0, "sample_size": 85, "median_impact": 10.0, "p25_impact": 3.0, "p75_impact": 19.0, "source": "Subscription Economy Index", "notes": "Pause subscription option reduces cancellations 15-25%"},

    {"industry": "consumer_sub", "stage": "series_a", "decision_type": "hiring", "success_rate": 55.0, "sample_size": 120, "median_impact": 10.0, "p25_impact": 4.0, "p75_impact": 18.0, "source": "Subscription Economy Index", "notes": "CRO/data analytics leader drives conversion optimization"},
    {"industry": "consumer_sub", "stage": "series_a", "decision_type": "pricing", "success_rate": 65.0, "sample_size": 110, "median_impact": 13.0, "p25_impact": 5.0, "p75_impact": 24.0, "source": "Zuora Subscription Economy Report", "notes": "Family/team plans expand wallet share 2-3x"},
    {"industry": "consumer_sub", "stage": "series_a", "decision_type": "growth", "success_rate": 58.0, "sample_size": 140, "median_impact": 14.0, "p25_impact": 5.0, "p75_impact": 26.0, "source": "Startup Genome Report 2024", "notes": "App Store Optimization + paid mobile acquisition scaling"},
    {"industry": "consumer_sub", "stage": "series_a", "decision_type": "product", "success_rate": 60.0, "sample_size": 110, "median_impact": 12.0, "p25_impact": 4.0, "p75_impact": 22.0, "source": "First Round State of Startups 2024", "notes": "AI personalization increases engagement 30-50%"},
    {"industry": "consumer_sub", "stage": "series_a", "decision_type": "fundraising", "success_rate": 48.0, "sample_size": 180, "median_impact": 17.0, "p25_impact": 6.0, "p75_impact": 32.0, "source": "CB Insights Venture Report 2024", "notes": "LTV:CAC >3x and <12mo payback period expected"},
    {"industry": "consumer_sub", "stage": "series_a", "decision_type": "cost_reduction", "success_rate": 62.0, "sample_size": 85, "median_impact": 8.0, "p25_impact": 3.0, "p75_impact": 15.0, "source": "Zuora Subscription Economy Report", "notes": "Content cost amortization across larger subscriber base"},
    {"industry": "consumer_sub", "stage": "series_a", "decision_type": "retention", "success_rate": 58.0, "sample_size": 100, "median_impact": 12.0, "p25_impact": 5.0, "p75_impact": 22.0, "source": "Subscription Economy Index", "notes": "Personalized win-back campaigns recover 10-20% churned users"},

    {"industry": "consumer_sub", "stage": "series_b_plus", "decision_type": "hiring", "success_rate": 58.0, "sample_size": 150, "median_impact": 12.0, "p25_impact": 4.0, "p75_impact": 22.0, "source": "Subscription Economy Index", "notes": "Brand marketing leader for mass-market awareness campaigns"},
    {"industry": "consumer_sub", "stage": "series_b_plus", "decision_type": "pricing", "success_rate": 70.0, "sample_size": 130, "median_impact": 15.0, "p25_impact": 6.0, "p75_impact": 28.0, "source": "Zuora Subscription Economy Report", "notes": "Premium tier at 3x base price captures 15-25% of subscribers"},
    {"industry": "consumer_sub", "stage": "series_b_plus", "decision_type": "growth", "success_rate": 60.0, "sample_size": 170, "median_impact": 16.0, "p25_impact": 6.0, "p75_impact": 30.0, "source": "Startup Genome Report 2024", "notes": "TV/brand advertising becomes ROI-positive at scale"},
    {"industry": "consumer_sub", "stage": "series_b_plus", "decision_type": "product", "success_rate": 62.0, "sample_size": 130, "median_impact": 14.0, "p25_impact": 5.0, "p75_impact": 26.0, "source": "First Round State of Startups 2024", "notes": "Content library depth drives long-term retention"},
    {"industry": "consumer_sub", "stage": "series_b_plus", "decision_type": "fundraising", "success_rate": 52.0, "sample_size": 210, "median_impact": 20.0, "p25_impact": 8.0, "p75_impact": 38.0, "source": "CB Insights Venture Report 2024", "notes": "Path to profitability with clear unit economics trajectory"},
    {"industry": "consumer_sub", "stage": "series_b_plus", "decision_type": "cost_reduction", "success_rate": 65.0, "sample_size": 110, "median_impact": 10.0, "p25_impact": 4.0, "p75_impact": 18.0, "source": "Zuora Subscription Economy Report", "notes": "ML-driven content recommendations reduce production waste"},
    {"industry": "consumer_sub", "stage": "series_b_plus", "decision_type": "retention", "success_rate": 62.0, "sample_size": 120, "median_impact": 14.0, "p25_impact": 5.0, "p75_impact": 26.0, "source": "Subscription Economy Index", "notes": "Community features create social lock-in reducing churn 30%"},

    # ── Hardware ──────────────────────────────────────────────────────
    {"industry": "hardware", "stage": "pre_seed", "decision_type": "hiring", "success_rate": 48.0, "sample_size": 55, "median_impact": 7.0, "p25_impact": 2.0, "p75_impact": 14.0, "source": "HAX Accelerator Report", "notes": "Mechanical + electrical engineering co-founders critical"},
    {"industry": "hardware", "stage": "pre_seed", "decision_type": "pricing", "success_rate": 50.0, "sample_size": 50, "median_impact": 8.0, "p25_impact": 2.0, "p75_impact": 16.0, "source": "Bolt Hardware Report", "notes": "Hardware margin target 40%+ to sustain R&D investment"},
    {"industry": "hardware", "stage": "pre_seed", "decision_type": "product", "success_rate": 45.0, "sample_size": 65, "median_impact": 8.0, "p25_impact": 2.0, "p75_impact": 16.0, "source": "HAX Accelerator Report", "notes": "Functional prototype before manufacturing design"},
    {"industry": "hardware", "stage": "pre_seed", "decision_type": "fundraising", "success_rate": 35.0, "sample_size": 100, "median_impact": 12.0, "p25_impact": 4.0, "p75_impact": 24.0, "source": "CB Insights Venture Report 2024", "notes": "Hardware pre-seed increasingly requires working prototype"},
    {"industry": "hardware", "stage": "pre_seed", "decision_type": "growth", "success_rate": 40.0, "sample_size": 55, "median_impact": 7.0, "p25_impact": 2.0, "p75_impact": 14.0, "source": "Startup Genome Report 2024", "notes": "Crowdfunding validates demand before manufacturing"},
    {"industry": "hardware", "stage": "pre_seed", "decision_type": "cost_reduction", "success_rate": 55.0, "sample_size": 45, "median_impact": 5.0, "p25_impact": 2.0, "p75_impact": 10.0, "source": "Bolt Hardware Report", "notes": "3D printing for prototyping reduces NRE by 70%"},
    {"industry": "hardware", "stage": "pre_seed", "decision_type": "retention", "success_rate": 50.0, "sample_size": 50, "median_impact": 8.0, "p25_impact": 2.0, "p75_impact": 16.0, "source": "HAX Accelerator Report", "notes": "Software/services layer critical for ongoing engagement"},

    {"industry": "hardware", "stage": "seed", "decision_type": "hiring", "success_rate": 52.0, "sample_size": 80, "median_impact": 8.0, "p25_impact": 3.0, "p75_impact": 16.0, "source": "HAX Accelerator Report", "notes": "Manufacturing engineer hire reduces COGS 15-25%"},
    {"industry": "hardware", "stage": "seed", "decision_type": "pricing", "success_rate": 55.0, "sample_size": 70, "median_impact": 10.0, "p25_impact": 3.0, "p75_impact": 18.0, "source": "Bolt Hardware Report", "notes": "Subscription/consumable model improves unit economics"},
    {"industry": "hardware", "stage": "seed", "decision_type": "product", "success_rate": 50.0, "sample_size": 85, "median_impact": 9.0, "p25_impact": 3.0, "p75_impact": 18.0, "source": "HAX Accelerator Report", "notes": "DFM (design for manufacturing) reduces production issues 60%"},
    {"industry": "hardware", "stage": "seed", "decision_type": "fundraising", "success_rate": 40.0, "sample_size": 130, "median_impact": 14.0, "p25_impact": 5.0, "p75_impact": 28.0, "source": "CB Insights Venture Report 2024", "notes": "Pre-orders + manufacturing partner required for seed"},
    {"industry": "hardware", "stage": "seed", "decision_type": "growth", "success_rate": 45.0, "sample_size": 75, "median_impact": 9.0, "p25_impact": 3.0, "p75_impact": 18.0, "source": "Startup Genome Report 2024", "notes": "Strategic channel partnerships outperform direct sales early"},
    {"industry": "hardware", "stage": "seed", "decision_type": "cost_reduction", "success_rate": 58.0, "sample_size": 65, "median_impact": 7.0, "p25_impact": 2.0, "p75_impact": 13.0, "source": "Bolt Hardware Report", "notes": "Contract manufacturer optimization biggest cost lever"},
    {"industry": "hardware", "stage": "seed", "decision_type": "retention", "success_rate": 52.0, "sample_size": 60, "median_impact": 9.0, "p25_impact": 3.0, "p75_impact": 18.0, "source": "HAX Accelerator Report", "notes": "OTA updates and firmware improvements retain customers"},

    {"industry": "hardware", "stage": "series_a", "decision_type": "hiring", "success_rate": 55.0, "sample_size": 105, "median_impact": 10.0, "p25_impact": 4.0, "p75_impact": 18.0, "source": "HAX Accelerator Report", "notes": "VP Operations from scaled hardware companies adds execution speed"},
    {"industry": "hardware", "stage": "series_a", "decision_type": "pricing", "success_rate": 58.0, "sample_size": 90, "median_impact": 12.0, "p25_impact": 4.0, "p75_impact": 22.0, "source": "Bolt Hardware Report", "notes": "Enterprise/B2B pricing 3-5x consumer margins"},
    {"industry": "hardware", "stage": "series_a", "decision_type": "product", "success_rate": 55.0, "sample_size": 100, "median_impact": 11.0, "p25_impact": 4.0, "p75_impact": 20.0, "source": "HAX Accelerator Report", "notes": "Second generation product reduces BOM cost 30-40%"},
    {"industry": "hardware", "stage": "series_a", "decision_type": "fundraising", "success_rate": 45.0, "sample_size": 160, "median_impact": 17.0, "p25_impact": 6.0, "p75_impact": 32.0, "source": "CB Insights Venture Report 2024", "notes": "Proven unit economics and channel partnerships required"},
    {"industry": "hardware", "stage": "series_a", "decision_type": "growth", "success_rate": 50.0, "sample_size": 100, "median_impact": 11.0, "p25_impact": 4.0, "p75_impact": 20.0, "source": "Startup Genome Report 2024", "notes": "Retail channel expansion after direct-to-consumer validation"},
    {"industry": "hardware", "stage": "series_a", "decision_type": "cost_reduction", "success_rate": 62.0, "sample_size": 85, "median_impact": 9.0, "p25_impact": 3.0, "p75_impact": 16.0, "source": "Bolt Hardware Report", "notes": "Volume manufacturing negotiation reduces BOM 20-30%"},
    {"industry": "hardware", "stage": "series_a", "decision_type": "retention", "success_rate": 58.0, "sample_size": 80, "median_impact": 11.0, "p25_impact": 4.0, "p75_impact": 20.0, "source": "HAX Accelerator Report", "notes": "Consumables/accessories model drives repeat revenue"},

    {"industry": "hardware", "stage": "series_b_plus", "decision_type": "hiring", "success_rate": 58.0, "sample_size": 130, "median_impact": 12.0, "p25_impact": 4.0, "p75_impact": 22.0, "source": "HAX Accelerator Report", "notes": "Supply chain VP from consumer electronics scales operations"},
    {"industry": "hardware", "stage": "series_b_plus", "decision_type": "pricing", "success_rate": 62.0, "sample_size": 110, "median_impact": 14.0, "p25_impact": 5.0, "p75_impact": 25.0, "source": "Bolt Hardware Report", "notes": "Platform ecosystem pricing (hardware + software + services)"},
    {"industry": "hardware", "stage": "series_b_plus", "decision_type": "product", "success_rate": 58.0, "sample_size": 120, "median_impact": 13.0, "p25_impact": 5.0, "p75_impact": 24.0, "source": "HAX Accelerator Report", "notes": "Product line expansion into adjacent form factors"},
    {"industry": "hardware", "stage": "series_b_plus", "decision_type": "fundraising", "success_rate": 48.0, "sample_size": 190, "median_impact": 20.0, "p25_impact": 8.0, "p75_impact": 38.0, "source": "CB Insights Venture Report 2024", "notes": "Gross margin trajectory and software revenue mix key metrics"},
    {"industry": "hardware", "stage": "series_b_plus", "decision_type": "growth", "success_rate": 55.0, "sample_size": 140, "median_impact": 14.0, "p25_impact": 5.0, "p75_impact": 26.0, "source": "Startup Genome Report 2024", "notes": "International distribution partnerships for scale"},
    {"industry": "hardware", "stage": "series_b_plus", "decision_type": "cost_reduction", "success_rate": 65.0, "sample_size": 100, "median_impact": 10.0, "p25_impact": 4.0, "p75_impact": 18.0, "source": "Bolt Hardware Report", "notes": "In-house manufacturing for high-margin components"},
    {"industry": "hardware", "stage": "series_b_plus", "decision_type": "retention", "success_rate": 60.0, "sample_size": 95, "median_impact": 13.0, "p25_impact": 5.0, "p75_impact": 24.0, "source": "HAX Accelerator Report", "notes": "Ecosystem lock-in through proprietary accessories/software"},

    # ── Services ──────────────────────────────────────────────────────
    {"industry": "services", "stage": "pre_seed", "decision_type": "hiring", "success_rate": 55.0, "sample_size": 70, "median_impact": 8.0, "p25_impact": 2.0, "p75_impact": 15.0, "source": "McKinsey Professional Services Report", "notes": "Domain expert hires establish credibility and attract clients"},
    {"industry": "services", "stage": "pre_seed", "decision_type": "pricing", "success_rate": 60.0, "sample_size": 65, "median_impact": 10.0, "p25_impact": 3.0, "p75_impact": 18.0, "source": "Toptal Industry Report", "notes": "Value-based pricing outperforms hourly billing 2-3x on margin"},
    {"industry": "services", "stage": "pre_seed", "decision_type": "growth", "success_rate": 58.0, "sample_size": 75, "median_impact": 9.0, "p25_impact": 3.0, "p75_impact": 18.0, "source": "Startup Genome Report 2024", "notes": "Referral-driven growth is most cost-effective channel"},
    {"industry": "services", "stage": "pre_seed", "decision_type": "product", "success_rate": 52.0, "sample_size": 60, "median_impact": 8.0, "p25_impact": 2.0, "p75_impact": 16.0, "source": "McKinsey Professional Services Report", "notes": "Productized services create scalable delivery model"},
    {"industry": "services", "stage": "pre_seed", "decision_type": "fundraising", "success_rate": 32.0, "sample_size": 90, "median_impact": 10.0, "p25_impact": 3.0, "p75_impact": 20.0, "source": "CB Insights Venture Report 2024", "notes": "Services businesses harder to fund; tech-enabled angle needed"},
    {"industry": "services", "stage": "pre_seed", "decision_type": "cost_reduction", "success_rate": 62.0, "sample_size": 55, "median_impact": 6.0, "p25_impact": 2.0, "p75_impact": 12.0, "source": "Toptal Industry Report", "notes": "Remote delivery reduces overhead 30-40%"},
    {"industry": "services", "stage": "pre_seed", "decision_type": "retention", "success_rate": 58.0, "sample_size": 60, "median_impact": 9.0, "p25_impact": 3.0, "p75_impact": 18.0, "source": "McKinsey Professional Services Report", "notes": "Retainer models create predictable recurring revenue"},

    {"industry": "services", "stage": "seed", "decision_type": "hiring", "success_rate": 55.0, "sample_size": 95, "median_impact": 9.0, "p25_impact": 3.0, "p75_impact": 16.0, "source": "McKinsey Professional Services Report", "notes": "Junior talent leverage improves margins when paired with senior oversight"},
    {"industry": "services", "stage": "seed", "decision_type": "pricing", "success_rate": 62.0, "sample_size": 85, "median_impact": 11.0, "p25_impact": 4.0, "p75_impact": 20.0, "source": "Toptal Industry Report", "notes": "Outcome-based pricing increases deal size 40-60%"},
    {"industry": "services", "stage": "seed", "decision_type": "growth", "success_rate": 55.0, "sample_size": 100, "median_impact": 11.0, "p25_impact": 4.0, "p75_impact": 20.0, "source": "Startup Genome Report 2024", "notes": "Thought leadership content drives inbound leads"},
    {"industry": "services", "stage": "seed", "decision_type": "product", "success_rate": 55.0, "sample_size": 80, "median_impact": 9.0, "p25_impact": 3.0, "p75_impact": 18.0, "source": "McKinsey Professional Services Report", "notes": "Automation of repeatable workflows increases margins 15-25%"},
    {"industry": "services", "stage": "seed", "decision_type": "fundraising", "success_rate": 35.0, "sample_size": 120, "median_impact": 12.0, "p25_impact": 4.0, "p75_impact": 24.0, "source": "CB Insights Venture Report 2024", "notes": "Technology platform differentiator required for VC interest"},
    {"industry": "services", "stage": "seed", "decision_type": "cost_reduction", "success_rate": 62.0, "sample_size": 70, "median_impact": 7.0, "p25_impact": 2.0, "p75_impact": 13.0, "source": "Toptal Industry Report", "notes": "AI-assisted delivery reduces cost per engagement 20-30%"},
    {"industry": "services", "stage": "seed", "decision_type": "retention", "success_rate": 60.0, "sample_size": 80, "median_impact": 10.0, "p25_impact": 4.0, "p75_impact": 19.0, "source": "McKinsey Professional Services Report", "notes": "Multi-service engagements increase retention 3x over single-project"},

    {"industry": "services", "stage": "series_a", "decision_type": "hiring", "success_rate": 58.0, "sample_size": 120, "median_impact": 10.0, "p25_impact": 4.0, "p75_impact": 18.0, "source": "McKinsey Professional Services Report", "notes": "Delivery managers enable margin improvement at scale"},
    {"industry": "services", "stage": "series_a", "decision_type": "pricing", "success_rate": 65.0, "sample_size": 100, "median_impact": 13.0, "p25_impact": 5.0, "p75_impact": 24.0, "source": "Toptal Industry Report", "notes": "Platform subscription + implementation services hybrid model"},
    {"industry": "services", "stage": "series_a", "decision_type": "growth", "success_rate": 58.0, "sample_size": 120, "median_impact": 13.0, "p25_impact": 5.0, "p75_impact": 24.0, "source": "Startup Genome Report 2024", "notes": "Partner network extends reach without proportional cost"},
    {"industry": "services", "stage": "series_a", "decision_type": "product", "success_rate": 58.0, "sample_size": 100, "median_impact": 11.0, "p25_impact": 4.0, "p75_impact": 20.0, "source": "McKinsey Professional Services Report", "notes": "SaaS product alongside services increases valuation multiples"},
    {"industry": "services", "stage": "series_a", "decision_type": "fundraising", "success_rate": 40.0, "sample_size": 150, "median_impact": 15.0, "p25_impact": 5.0, "p75_impact": 28.0, "source": "CB Insights Venture Report 2024", "notes": "Software revenue mix must show growth to attract VC"},
    {"industry": "services", "stage": "series_a", "decision_type": "cost_reduction", "success_rate": 65.0, "sample_size": 85, "median_impact": 9.0, "p25_impact": 3.0, "p75_impact": 16.0, "source": "Toptal Industry Report", "notes": "Nearshore talent + AI tooling reduces delivery cost 25-35%"},
    {"industry": "services", "stage": "series_a", "decision_type": "retention", "success_rate": 62.0, "sample_size": 95, "median_impact": 12.0, "p25_impact": 5.0, "p75_impact": 22.0, "source": "McKinsey Professional Services Report", "notes": "Embedded teams model creates dependency and high retention"},

    {"industry": "services", "stage": "series_b_plus", "decision_type": "hiring", "success_rate": 60.0, "sample_size": 150, "median_impact": 12.0, "p25_impact": 4.0, "p75_impact": 22.0, "source": "McKinsey Professional Services Report", "notes": "Industry vertical leaders open enterprise accounts"},
    {"industry": "services", "stage": "series_b_plus", "decision_type": "pricing", "success_rate": 68.0, "sample_size": 120, "median_impact": 15.0, "p25_impact": 6.0, "p75_impact": 28.0, "source": "Toptal Industry Report", "notes": "Managed services with SLA guarantees command premium pricing"},
    {"industry": "services", "stage": "series_b_plus", "decision_type": "growth", "success_rate": 60.0, "sample_size": 150, "median_impact": 15.0, "p25_impact": 5.0, "p75_impact": 28.0, "source": "Startup Genome Report 2024", "notes": "M&A of niche consultancies accelerates market coverage"},
    {"industry": "services", "stage": "series_b_plus", "decision_type": "product", "success_rate": 62.0, "sample_size": 120, "median_impact": 13.0, "p25_impact": 5.0, "p75_impact": 24.0, "source": "McKinsey Professional Services Report", "notes": "IP-driven frameworks differentiate from commodity services"},
    {"industry": "services", "stage": "series_b_plus", "decision_type": "fundraising", "success_rate": 45.0, "sample_size": 180, "median_impact": 18.0, "p25_impact": 7.0, "p75_impact": 34.0, "source": "CB Insights Venture Report 2024", "notes": "Services-to-platform transformation narrative for growth equity"},
    {"industry": "services", "stage": "series_b_plus", "decision_type": "cost_reduction", "success_rate": 68.0, "sample_size": 110, "median_impact": 10.0, "p25_impact": 4.0, "p75_impact": 18.0, "source": "Toptal Industry Report", "notes": "Proprietary tooling reduces cost per delivery 30-45%"},
    {"industry": "services", "stage": "series_b_plus", "decision_type": "retention", "success_rate": 65.0, "sample_size": 110, "median_impact": 14.0, "p25_impact": 5.0, "p75_impact": 26.0, "source": "McKinsey Professional Services Report", "notes": "Multi-year MSA contracts with expansion clauses"},
]


def seed_research_patterns(db: Session):
    now = datetime.utcnow()
    inserted = 0
    updated = 0
    for p in RESEARCH_PATTERNS:
        metadata = {"source": p["source"], "notes": p.get("notes", "")}
        existing = db.execute(
            text("""
                SELECT id FROM cross_company_patterns
                WHERE pattern_type='research' AND industry=:industry AND stage=:stage AND decision_type=:dt
            """),
            {"industry": p["industry"], "stage": p["stage"], "dt": p["decision_type"]},
        ).fetchone()
        if existing:
            db.execute(
                text("""
                    UPDATE cross_company_patterns
                    SET success_rate=:sr, sample_size=:ss, median_impact=:mi,
                        p25_impact=:p25, p75_impact=:p75, metadata_json=:mj,
                        computed_at=:now
                    WHERE id=:id
                """),
                {
                    "sr": p["success_rate"], "ss": p["sample_size"],
                    "mi": p["median_impact"], "p25": p["p25_impact"],
                    "p75": p["p75_impact"], "mj": json.dumps(metadata),
                    "now": now, "id": existing[0],
                },
            )
            updated += 1
        else:
            db.execute(
                text("""
                    INSERT INTO cross_company_patterns
                        (pattern_type, industry, stage, decision_type, sample_size,
                         success_rate, median_impact, p25_impact, p75_impact,
                         metadata_json, contributing_companies, computed_at)
                    VALUES
                        ('research', :industry, :stage, :decision_type, :sample_size,
                         :success_rate, :median_impact, :p25_impact, :p75_impact,
                         :metadata_json, 0, :computed_at)
                """),
                {
                    "industry": p["industry"],
                    "stage": p["stage"],
                    "decision_type": p["decision_type"],
                    "sample_size": p["sample_size"],
                    "success_rate": p["success_rate"],
                    "median_impact": p["median_impact"],
                    "p25_impact": p["p25_impact"],
                    "p75_impact": p["p75_impact"],
                    "metadata_json": json.dumps(metadata),
                    "computed_at": now,
                },
            )
            inserted += 1

    db.commit()
