export const blogPosts = [
  { slug: "finmark-shut-down-alternative", title: "Finmark Is Gone. Here's Where Your Runway Model Goes Next.", excerpt: "BILL sunset Finmark on 1 April 2026. Pry, Causal and Mosaic were absorbed too, and Runway just lost its domain. Here's what actually happened to startup FP&A — and what a seed-stage founder should do about it.", date: "Aug 8, 2026", author: "Vishesh Khurana" },
  { slug: "how-to-calculate-startup-runway", title: "How to Calculate Startup Runway: The Complete Guide for Founders", excerpt: "Runway is the single most important number for any startup. This guide covers the basic formula, common pitfalls, and why Monte Carlo simulation gives you a more accurate picture than a spreadsheet ever could.", date: "Mar 15, 2026", author: "Vishesh Khurana" },
  { slug: "seed-stage-saas-benchmarks-2026", title: "Seed-Stage SaaS Benchmarks 2026: What Good Looks Like", excerpt: "Updated benchmarks for seed-stage SaaS companies in 2026, covering ARR growth, net revenue retention, burn multiples, and the metrics that matter most for your next raise.", date: "Mar 12, 2026", author: "Vishesh Khurana" },
  { slug: "founderconsole-vs-sturppy-vs-finmark-vs-causal", title: "FounderConsole vs Sturppy vs Finmark vs Causal: 2026 Comparison", excerpt: "A detailed comparison of the top financial planning tools for startups in 2026. We compare features, pricing, ease of use, and which tool is best for different stages and needs.", date: "Mar 10, 2026", author: "Vishesh Khurana" },
  { slug: "best-ai-tools-startup-financial-planning", title: "7 Best AI Tools for Startup Financial Planning in 2026", excerpt: "A curated list of the best AI-powered tools for startup financial planning, from runway forecasting to board deck generation.", date: "Mar 8, 2026", author: "Vishesh Khurana" },
  { slug: "what-if-analysis-for-startups", title: "What-If Analysis for Startups: A Founder's Guide", excerpt: "Learn how to use what-if analysis to test hiring plans, pricing changes, and fundraising timing before committing.", date: "Mar 5, 2026", author: "Vishesh Khurana" },
  { slug: "board-deck-30-minutes", title: "How to Prepare a Board Deck in 30 Minutes", excerpt: "A step-by-step guide to preparing an investor-ready board deck in 30 minutes or less.", date: "Mar 3, 2026", author: "Vishesh Khurana" },
  { slug: "digital-twin-for-startups", title: "Digital Twin for Startups: The Future of Founder Decision-Making", excerpt: "Learn what a digital twin is, how it applies to startups, and why having a live financial model of your company changes how you make decisions.", date: "Feb 28, 2026", author: "Vishesh Khurana" },
  { slug: "ltv-cac-ratio-explained", title: "LTV:CAC Ratio Explained for SaaS Founders", excerpt: "The LTV:CAC ratio is one of the most important unit economics metrics for SaaS. This guide explains how to calculate it, what good looks like, and how to improve it.", date: "Feb 25, 2026", author: "Vishesh Khurana" },
  { slug: "calculate-true-runway", title: "How to Calculate Your True Runway", excerpt: "A single forecast is a trap. Learn how to build defensible runway scenarios using confidence intervals instead of gut feel.", date: "Feb 24, 2026", author: "Nikita Kapoor" },
  { slug: "monte-carlo-founders-guide", title: "Monte Carlo Simulations: A Founder's Guide", excerpt: "A plain-English explanation that turns Monte Carlo from intimidating to practical.", date: "Feb 18, 2026", author: "Arjun Rao" },
  { slug: "cap-table-mistakes", title: "5 Cap Table Mistakes That Cost Founders Millions", excerpt: "From uncapped SAFEs to missing pro-rata rights — the most common equity mistakes early-stage founders make.", date: "Feb 10, 2026", author: "Priya Sharma" },
  { slug: "timing-series-a", title: "When to Raise: Timing Your Series A", excerpt: "How confidence intervals help you avoid raising too early or too late.", date: "Jan 29, 2026", author: "Nikita Kapoor" },
  { slug: "data-driven-culture", title: "Building a Data-Driven Culture", excerpt: "The best founders don't just track metrics — they build systems where every team member understands the numbers.", date: "Jan 15, 2026", author: "Dev Mehta" },
  { slug: "unit-economics-guide", title: "The Founder's Guide to Unit Economics", excerpt: "LTV, CAC, payback period, and contribution margin explained with real startup examples.", date: "Jan 6, 2026", author: "Priya Sharma" },
];

export const blogPostContent: Record<string, string[]> = {
  "finmark-shut-down-alternative": [
    "If you went looking for finmark.com recently, you landed on bill.com's homepage. No migration guide, no explanation, no page acknowledging that Finmark ever existed. BILL sunset the product on 1 April 2026, and bill.com/finmark returns a 404 today.",
    "Over the past four years, essentially every financial planning tool built for early-stage startups has been acquired and folded into something larger and more expensive. Not one of them left a forwarding address that a seed-stage founder can use.",
    "## Where the startup FP&A tools went",
    "Finmark was sunset by BILL on 1 April 2026 and finmark.com now redirects to the bill.com homepage, with no Finmark destination page anywhere on the site. Pry was acquired by Brex for $90M and its deep links now 404 outright. Causal was acquired by Lucanet in October 2024 and redirects to an enterprise Extended Planning & Analysis page. Mosaic was acquired by HiBob for around $35M and is now a module inside an HR suite. And on 22 July 2026, Runway Financial lost the runway.com domain to Runway AI, the video-generation company.",
    "## The part that actually matters",
    "It would be easy to read that list as consolidation. It isn't. It's a migration upmarket. Runway's pricing page publishes no prices, no free tier, and no self-serve signup, and its paid landing pages segment audiences as 50-500, 500-1,500, and 1,500+ employees. Jirav, the only tool still operating independently, sells to accounting firms and does not use the words runway or burn rate on its homepage.",
    "None of these companies did anything wrong. Enterprise FP&A is a better business than seed FP&A. But it leaves a specific person stranded: the founder with three employees, nine months of cash, and a board meeting in a fortnight.",
    "## What a spreadsheet actually costs you",
    "A spreadsheet gives you a single line: we run out of money in month nine. It cannot tell you the odds. Real runway is a distribution, not a date, and a single-point forecast hides exactly the risk you are trying to reason about. It also goes stale, and it cannot answer the question founders actually ask, which is always some version of: if we do this thing, what happens?",
    "## What to do this week",
    "Export your historical actuals to CSV while you still can. Separate measured numbers from assumed ones. And insist on a range rather than a date: if a tool tells you 7.8 months and cannot tell you the tenth and ninetieth percentile, it is giving you false precision.",
    "## Where FounderConsole fits",
    "FounderConsole was built for the founder the rest of the market left behind. Upload a CSV of your monthly financials and get a runway distribution with P10, P50 and P90 bands rather than a single date. Model scenarios directly. Metrics that cannot be computed honestly from your data are marked as estimates or shown as N/A rather than invented. The runway calculator is free, with no signup and no demo gate.",
  ],
  "how-to-calculate-startup-runway": [
    "Every startup founder eventually confronts the same question: how long can we keep going before we run out of money? The answer is your runway, and calculating it correctly can mean the difference between a well-timed fundraise and a fire sale.",
    "## The Basic Runway Formula",
    "At its simplest, startup runway equals your current cash balance divided by your monthly net burn rate. Net burn is total monthly expenses minus total monthly revenue. If you have $600,000 in the bank and you spend $80,000 per month while earning $30,000, your net burn is $50,000 and your runway is 12 months.",
    "This formula is useful as a starting point, but it carries a dangerous assumption: that your burn rate stays constant. In practice, burn fluctuates. Revenue is lumpy. Contracts slip. Hires start at different times.",
    "## Why Static Calculations Fail",
    "Consider a real scenario. You calculate 14 months of runway based on current numbers. But next quarter, a key customer churns, reducing revenue by $8,000 per month. You also onboard two engineers, adding $25,000 in monthly payroll. Suddenly your net burn jumps from $50,000 to $83,000, and your runway drops to 7 months.",
    "## The Monte Carlo Approach",
    "Instead of calculating a single runway number, sophisticated founders use Monte Carlo simulation. This technique runs your financial model thousands of times, each with slightly different inputs drawn from realistic probability distributions. The result is a probability distribution showing your P10 (pessimistic), P50 (median), and P90 (optimistic) runway.",
    "## Key Variables That Affect Runway",
    "Revenue growth rate is the single biggest lever. Customer churn works in the opposite direction. Hiring pace is usually the largest controllable expense. Payment terms and accounts receivable also matter.",
    "## Practical Steps for Founders",
    "Start by connecting your actual financial data rather than working from estimates. Calculate your gross and net burn rates over the past six months. Then project forward with multiple scenarios: baseline, optimistic, and pessimistic.",
  ],
  "seed-stage-saas-benchmarks-2026": [
    "If you are raising a seed round or just closed one, you need to know where you stand relative to other companies at your stage.",
    "## ARR and Revenue Growth",
    "At the seed stage in 2026, the median SaaS company has between $100K and $500K in annual recurring revenue. The top quartile is growing at 15-20% month-over-month, while the median is closer to 8-12%.",
    "## Net Revenue Retention (NRR)",
    "Net revenue retention measures how much revenue you keep and grow from existing customers. For seed-stage SaaS, good NRR is above 100%. The top quartile achieves 110-120% NRR.",
    "## Burn Multiple",
    "Burn multiple is net new ARR divided by net burn. A burn multiple below 2x is excellent at seed stage. Between 2x and 4x is acceptable. Above 4x is a warning sign.",
    "## Gross Margin",
    "SaaS gross margins should be between 70% and 85%. Below 65%, investors will question whether your business is truly a software company.",
    "## CAC Payback Period",
    "At seed stage, CAC payback should be under 18 months. The median is 12-14 months.",
  ],
  "founderconsole-vs-sturppy-vs-finmark-vs-causal": [
    "Choosing the right financial planning tool is one of the most consequential decisions a startup founder makes.",
    "## Overview of Each Tool",
    "FounderConsole is an AI-powered financial intelligence platform with 37 integrations, Monte Carlo simulation, AI copilot, and cap table management. Sturppy focuses on financial modeling templates. Finmark was acquired by BILL in 2023. Causal is a general-purpose modeling tool.",
    "## Data Integration",
    "FounderConsole leads with 37 production connectors. Sturppy offers limited integrations. Causal requires manual data import.",
    "## Simulation and Forecasting",
    "FounderConsole runs Monte Carlo simulations with 1,000+ iterations producing P10/P50/P90 confidence bands. Other tools produce deterministic single-line projections.",
    "## AI Capabilities",
    "FounderConsole includes a multi-agent AI copilot powered by multiple LLMs with intelligent task routing. Other tools offer basic or no AI features.",
    "## Bottom Line",
    "For seed and Series A stage founders, FounderConsole offers the most comprehensive feature set at the best price (free during beta).",
  ],
  "best-ai-tools-startup-financial-planning": [
    "AI has transformed how startups approach financial planning. Here are the seven best AI-powered tools for startup financial planning in 2026.",
    "## 1. FounderConsole — Best All-in-One Platform",
    "Combines Monte Carlo simulation, multi-LLM AI copilot, 37 data connectors, cap table management, and a digital twin into a single platform.",
    "## 2. ChatGPT / Claude — Best for Ad-Hoc Analysis",
    "General-purpose LLMs excel at ad-hoc questions but lack real-time data integration.",
    "## 3. Runway (by Runway Financial) — Best for FP&A Teams",
    "Designed for finance teams rather than founders.",
    "## How to Choose the Right Tool",
    "For pre-seed and seed-stage founders who want one platform, FounderConsole is the clear choice — especially since it is free during beta.",
  ],
  "what-if-analysis-for-startups": [
    "Every startup founder makes decisions under uncertainty. What-if analysis helps you answer critical questions with data instead of gut feeling.",
    "## What Is What-If Analysis?",
    "What-if analysis is the process of modeling different decisions and seeing their projected outcomes.",
    "## Three Essential Scenarios Every Founder Should Model",
    "The first scenario is your hiring plan. The second is pricing changes. The third is fundraising timing.",
    "## From Deterministic to Probabilistic",
    "Monte Carlo simulation takes each scenario and runs it thousands of times with randomized inputs, producing a probability distribution.",
  ],
  "board-deck-30-minutes": [
    "Board meetings are important but preparing for them should not consume your entire week. With the right tools and structure, you can prepare an investor-ready board deck in 30 minutes.",
    "## The Essential Board Deck Structure",
    "A good board deck has seven sections: executive summary, key metrics, financial overview, product update, go-to-market update, team and hiring, and asks.",
    "## The 30-Minute Approach",
    "Step one: Connect your data sources. Step two: Use the Board Deck Generator. Step three: Review and customize. Step four: Export to PDF.",
  ],
  "digital-twin-for-startups": [
    "In manufacturing, a digital twin is a virtual replica of a physical system. The same concept is now transforming how startups make financial decisions.",
    "## What Is a Startup Digital Twin?",
    "A startup digital twin is a continuously updated virtual representation of your company. It ingests data from your accounting software, payment processor, banking, payroll, CRM to create a live financial model.",
    "## Why It Matters for Founders",
    "A digital twin gives you real-time accuracy, holistic visibility, and simulation capability that spreadsheets cannot provide.",
  ],
  "ltv-cac-ratio-explained": [
    "If investors could only look at one metric to evaluate your SaaS business, many would choose the LTV:CAC ratio.",
    "## What Is LTV:CAC?",
    "LTV stands for Lifetime Value. CAC stands for Customer Acquisition Cost. The LTV:CAC ratio divides the first by the second.",
    "## What Good Looks Like",
    "The benchmark for healthy SaaS economics is an LTV:CAC ratio of 3:1 or higher. Between 3:1 and 5:1 is the sweet spot.",
  ],
  "calculate-true-runway": [
    "Most founders calculate runway with a simple formula: cash in bank divided by monthly burn. That number feels precise. It's also dangerously wrong.",
    "## Why Confidence Intervals Matter",
    "Instead of asking how many months of runway do we have, you should ask what's the probability we survive 18 months.",
    "## The FounderConsole Approach",
    "Connect your financial data and we automatically calculate your baseline runway distribution with P10/P50/P90 confidence bands.",
  ],
  "monte-carlo-founders-guide": [
    "Monte Carlo simulation sounds like something from a physics textbook. In practice, it's one of the most practical tools a startup founder can use.",
    "## What It Actually Does",
    "A Monte Carlo simulation runs your model thousands of times, each time picking slightly different values for each input based on realistic ranges. After 1,000 runs, you get a distribution of answers.",
    "## Why Founders Should Care",
    "Investors increasingly expect probabilistic thinking. With Monte Carlo, you can answer: We have a 75% probability of reaching 12 months.",
  ],
  "cap-table-mistakes": [
    "Your cap table is the single most consequential document in your startup. Get it wrong early, and the compounding effects can cost you millions.",
    "## 1. Uncapped SAFEs Without Modeling the Dilution",
    "SAFEs are founder-friendly — until they're not. Always model the conversion scenarios before signing.",
    "## 2. Ignoring the Option Pool Shuffle",
    "Investors typically require a 10-20% option pool before their investment. This pool comes out of the pre-money valuation.",
    "## 3. Missing Pro-Rata Rights Documentation",
    "Keep a clean record from day one.",
    "## 4. Vesting Schedule Gaps",
    "Every founder should be on a four-year vesting schedule with a one-year cliff.",
    "## 5. Not Using Software to Track Changes",
    "Spreadsheet cap tables break. Use purpose-built cap table software.",
  ],
  "timing-series-a": [
    "Timing your fundraise is one of the highest-stakes decisions a founder makes.",
    "## The Traditional Approach Is Broken",
    "Most founders use rules of thumb that ignore the most important variable: uncertainty.",
    "## A Probabilistic Framework",
    "Instead of asking when should I raise, ask at what point does the probability of running out of cash before closing a round exceed my risk tolerance.",
  ],
  "data-driven-culture": [
    "Every startup says they're data-driven. Few actually are.",
    "## Metrics Without Context Are Noise",
    "Every metric needs three things: a clear owner, a target, and a decision framework.",
    "## The Weekly Metrics Review",
    "The single highest-leverage meeting at a startup is the weekly metrics review. Keep it to 30 minutes. Focus on 5-7 key metrics.",
  ],
  "unit-economics-guide": [
    "Unit economics tell you whether your business model actually works. Revenue growth can mask a broken model for a while.",
    "## Customer Acquisition Cost (CAC)",
    "CAC is the total cost of acquiring one new customer. A healthy SaaS startup should see CAC trending down over time.",
    "## Lifetime Value (LTV)",
    "LTV is the total revenue you expect from a customer over their entire relationship with you.",
    "## The LTV:CAC Ratio",
    "Investors want to see LTV:CAC of at least 3:1.",
  ],
};
