"""
MetricSuggestion model for storing recommended metrics based on connected data sources.
Suggestions are generated deterministically from connector capabilities.
"""

from sqlalchemy import Column, Integer, String, DateTime, JSON, ForeignKey, Index, Text
from sqlalchemy.sql import func
from server.core.db import Base


class MetricSuggestion(Base):
    """
    A suggested metric that can be created from connected data sources.
    Generated by the suggestion rule engine based on connector capabilities.
    """
    __tablename__ = "metric_suggestions"

    id = Column(Integer, primary_key=True, autoincrement=True)
    company_id = Column(Integer, ForeignKey("companies.id"), nullable=False, index=True)
    
    data_source_id = Column(Integer, nullable=True, index=True)
    
    suggestion_key = Column(String(100), nullable=False)
    title = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)
    
    category = Column(String(50), default="Finance")
    
    metric_dsl_yaml = Column(Text, nullable=False)
    
    dependencies = Column(JSON, nullable=True)
    
    confidence_score = Column(Integer, default=80)
    
    reason = Column(JSON, nullable=True)
    
    status = Column(String(50), default="new")
    
    accepted_metric_id = Column(Integer, ForeignKey("metric_definitions.id"), nullable=True)
    
    created_at = Column(DateTime, server_default=func.now(), nullable=False)
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())

    __table_args__ = (
        Index("ix_suggestion_company_key", "company_id", "suggestion_key", unique=True),
        Index("ix_suggestion_status", "status"),
        Index("ix_suggestion_category", "category"),
    )

    def to_dict(self):
        return {
            "id": self.id,
            "company_id": self.company_id,
            "data_source_id": self.data_source_id,
            "suggestion_key": self.suggestion_key,
            "title": self.title,
            "description": self.description,
            "category": self.category,
            "metric_dsl_yaml": self.metric_dsl_yaml,
            "dependencies": self.dependencies or [],
            "confidence_score": self.confidence_score,
            "reason": self.reason or {},
            "status": self.status,
            "accepted_metric_id": self.accepted_metric_id,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }


class SuggestionEvent(Base):
    """
    Audit log for suggestion-related actions (generated, viewed, accepted, dismissed).
    """
    __tablename__ = "suggestion_events"

    id = Column(Integer, primary_key=True, autoincrement=True)
    company_id = Column(Integer, ForeignKey("companies.id"), nullable=False, index=True)
    suggestion_id = Column(Integer, ForeignKey("metric_suggestions.id"), nullable=False, index=True)
    
    actor_id = Column(Integer, ForeignKey("users.id"), nullable=True)
    
    action = Column(String(50), nullable=False)
    
    meta = Column(JSON, nullable=True)
    
    created_at = Column(DateTime, server_default=func.now(), nullable=False)

    __table_args__ = (
        Index("ix_sugg_event_suggestion", "suggestion_id"),
        Index("ix_sugg_event_action", "action"),
    )

    def to_dict(self):
        return {
            "id": self.id,
            "company_id": self.company_id,
            "suggestion_id": self.suggestion_id,
            "actor_id": self.actor_id,
            "action": self.action,
            "meta": self.meta or {},
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }
